### ISSUE TITLE
Bug in method "attention_on_cat_and_numerical_feats"

### ISSUE THREAD

**Issue by Jordy-VL** [georgian-io/Multimodal-Toolkit#21] opened 2022-04-25 14:57 UTC
https://github.com/georgian-io/Multimodal-Toolkit/blob/8f5b64d586f8f13663cb88074001b316936f9e38/multimodal_transformers/model/tabular_combiner.py#L268

There is a bug in the method "attention_on_cat_and_numerical_feats", where if you have both categorical and numerical features, the MLP defined as `self.cat_mlp` gets overwritten instead of initializing `self.num_mlp`.

**Comment by akashsaravanan-georgian** [comment] 2023-03-03 18:07
Closing as this is a duplicate of #14.

**Closed by akashsaravanan-georgian** 2023-03-03 18:07 UTC
